# Generated by Django 5.2.17 on 2026-09-28 08:36

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_documents', '0001_initial'),
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalUpdate',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('new', 'New'), ('amended', 'Amended'), ('expired', 'Expired'), ('effective', 'Effective')], max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='legal_documents.legaldocument')),
                ('parser_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_updates', to='parsers.parserjob')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='legal_documents.legaldocumentversion')),
            ],
            options={
                'indexes': [models.Index(fields=['update_type', '-detected_at'], name='legal_monit_update__b6c33a_idx'), models.Index(fields=['document'], name='legal_monit_documen_553c66_idx')],
            },
        ),
    ]
