# Generated by Django 5.2.17 on 2026-09-28 08:36

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSource',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=300)),
                ('is_official', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('html', 'Html'), ('pdf', 'Pdf'), ('word', 'Word'), ('json', 'Json'), ('xml', 'Xml')], max_length=10)),
                ('url', models.CharField(max_length=600)),
                ('sha256', models.CharField(max_length=64)),
                ('object_key', models.CharField(max_length=300)),
                ('content_encoding', models.CharField(blank=True, max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='legal_sources.legalsource')),
            ],
            options={
                'indexes': [models.Index(fields=['url'], name='legal_sourc_url_e1aa28_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'sha256'), name='uniq_snapshot_source_sha256')],
            },
        ),
    ]
