# Generated by Django 5.2.17 on 2026-09-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_sources', '0002_snapshot_immutable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesnapshot',
            name='kind',
            field=models.CharField(choices=[('html', 'Html'), ('pdf', 'Pdf'), ('word', 'Word'), ('json', 'Json'), ('xml', 'Xml'), ('zip', 'Zip')], max_length=10),
        ),
    ]
