# Generated by Django 5.2.17 on 2026-09-28 08:36

import apps.common.ids
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_extensions_and_functions"),
        ('legal_documents', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('official_law', 'Official Law'), ('official_guidance', 'Official Guidance'), ('organization_internal', 'Organization Internal'), ('draft', 'Draft')], max_length=25)),
                ('knowledge_document_id', models.UUIDField(blank=True, null=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('search_text', models.TextField()),
                ('search_tsv', models.GeneratedField(db_persist=True, expression=models.Func(models.F('search_text'), function='to_tsvector', template="to_tsvector('simple'::regconfig, %(expressions)s)"), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('token_count', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('language', models.CharField(blank=True, max_length=2)),
                ('chunker_version', models.PositiveSmallIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='legal_documents.legaldocument')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='legal_documents.legaldocumentsection')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='legal_documents.legaldocumentversion')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='search_docu_organiz_faa0fa_idx'), models.Index(fields=['document'], name='search_docu_documen_c22bce_idx'), models.Index(fields=['source_type', 'language'], name='search_docu_source__50d886_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_tsv'], name='chunk_search_tsv_gin')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('source_type__in', ['official_law', 'official_guidance'])), models.Q(models.Q(('source_type__in', ['official_law', 'official_guidance']), _negated=True), ('organization__isnull', False)), _connector='OR'), name='chk_chunk_org_matches_source_type'), models.CheckConstraint(condition=models.Q(('version__isnull', False), ('knowledge_document_id__isnull', False), _connector='OR'), name='chk_chunk_has_owner'), models.UniqueConstraint(condition=models.Q(('version__isnull', False)), fields=('version', 'chunk_index'), name='uniq_chunk_version_index')],
            },
        ),
    ]
