# Generated by Django 5.2.17 on 2026-09-28 08:36

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_documents', '0001_initial'),
        ('legal_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserJob',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(default='manual', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed With Errors'), ('failed', 'Failed')], default='running', max_length=25)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parser_jobs', to='legal_sources.legalsource')),
            ],
        ),
        migrations.CreateModel(
            name='ParserItem',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=600)),
                ('external_id', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=10)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='legal_documents.legaldocument')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='legal_sources.sourcesnapshot')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='legal_documents.legaldocumentversion')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parsers.parserjob')),
            ],
        ),
        migrations.CreateModel(
            name='ParserError',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=600)),
                ('exception', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='legal_sources.legalsource')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='parsers.parseritem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='parsers.parserjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='parserjob',
            index=models.Index(fields=['-started_at'], name='parsers_par_started_033090_idx'),
        ),
        migrations.AddIndex(
            model_name='parseritem',
            index=models.Index(fields=['job', 'status'], name='parsers_par_job_id_8981ef_idx'),
        ),
        migrations.AddIndex(
            model_name='parseritem',
            index=models.Index(fields=['external_id'], name='parsers_par_externa_9ee662_idx'),
        ),
        migrations.AddIndex(
            model_name='parsererror',
            index=models.Index(fields=['job'], name='parsers_par_job_id_9cc695_idx'),
        ),
    ]
