# Generated by Django 5.2.17 on 2026-09-28 08:36

import apps.common.fields
import apps.common.ids
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_extensions_and_functions"),
        ('legal_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeRank',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_kind', models.CharField(default='card', max_length=10)),
                ('type_key', models.CharField(max_length=300)),
                ('form_key', models.CharField(blank=True, max_length=200)),
                ('rank', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key_kind', 'type_key', 'form_key'), name='uniq_rank_key')],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=32)),
                ('source_url', models.CharField(max_length=500)),
                ('language', models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('', 'Unknown')], max_length=2)),
                ('script', models.CharField(blank=True, choices=[('cyrl', 'Cyrillic'), ('latn', 'Latin'), ('', 'Unknown')], max_length=4)),
                ('language_source', models.CharField(blank=True, max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=64)),
                ('number_key', models.CharField(blank=True, max_length=64)),
                ('title', models.TextField()),
                ('document_type', models.CharField(blank=True, max_length=200)),
                ('document_form', models.CharField(blank=True, max_length=200)),
                ('authority', models.TextField(blank=True)),
                ('legal_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('adopted_at', models.DateField(blank=True, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('not_yet_effective', 'Not Yet Effective'), ('draft', 'Draft'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status_raw', models.CharField(blank=True, max_length=100)),
                ('representation', models.CharField(choices=[('html', 'Html'), ('pdf_only', 'Pdf Only')], max_length=10)),
                ('text_status', models.CharField(choices=[('ok', 'Ok'), ('stub', 'Stub'), ('needs_ocr', 'Needs Ocr'), ('empty', 'Empty')], max_length=10)),
                ('group_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_source_sha256', models.CharField(blank=True, max_length=64)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='legal_sources.legalsource')),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('edition_on', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('valid_from_source', models.CharField(choices=[('edition', 'Edition'), ('card_effective', 'Card Effective'), ('published', 'Published'), ('adopted', 'Adopted'), ('observed', 'Observed'), ('observed_adjusted', 'Observed Adjusted')], max_length=20)),
                ('valid_period', models.GeneratedField(db_persist=True, expression=models.Func(models.F('valid_from'), models.F('valid_to'), models.Value('[]'), function='daterange'), output_field=django.contrib.postgres.fields.ranges.DateRangeField())),
                ('is_current', models.BooleanField(default=False)),
                ('content_hash', models.CharField(max_length=64)),
                ('normalized_text', models.TextField(blank=True)),
                ('text_source', models.CharField(choices=[('html', 'Html'), ('pdf_embedded', 'Pdf Embedded'), ('ocr', 'Ocr')], max_length=15)),
                ('parser_version', models.PositiveSmallIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='legal_documents.legaldocument')),
                ('raw_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='legal_sources.sourcesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocumentSection',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('title', 'Title'), ('form', 'Form'), ('body', 'Body'), ('number', 'Number'), ('place_date', 'Place Date'), ('appendix', 'Appendix'), ('chapter', 'Chapter'), ('part', 'Part'), ('section', 'Section'), ('article', 'Article'), ('clause', 'Clause'), ('subclause', 'Subclause'), ('item', 'Item'), ('paragraph', 'Paragraph'), ('table', 'Table'), ('footnote', 'Footnote'), ('signature', 'Signature'), ('note', 'Note'), ('pdf_page', 'Pdf Page')], max_length=15)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('title', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField()),
                ('path', apps.common.fields.LTreeField()),
                ('source_anchor', models.CharField(blank=True, max_length=32)),
                ('text_hash', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='legal_documents.legaldocumentsection')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='legal_documents.legaldocumentversion')),
            ],
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='legal_documents.legaldocumentversion'),
        ),
        migrations.CreateModel(
            name='LegalDocumentCard',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('passport', 'Passport'), ('card1', 'Card1'), ('card2', 'Card2'), ('basrev', 'Basrev'), ('revhis', 'Revhis'), ('correspondents', 'Correspondents'), ('respondents', 'Respondents')], max_length=20)),
                ('raw_text', models.TextField()),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='legal_documents.legaldocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'kind'), name='uniq_card_kind')],
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentClassification',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('system', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('label', models.TextField()),
                ('fingerprint', models.CharField(max_length=32)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='legal_documents.legaldocument')),
            ],
            options={
                'indexes': [models.Index(fields=['system', 'code'], name='legal_docum_system_1acb1e_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'system', 'fingerprint'), name='uniq_classification')],
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentRelation',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.CharField(max_length=600)),
                ('target_external_id', models.CharField(blank=True, max_length=32)),
                ('target_edition_on', models.DateField(blank=True, null=True)),
                ('target_anchor', models.CharField(blank=True, max_length=64)),
                ('relation_type', models.CharField(choices=[('cites', 'Cites'), ('language_variant', 'Language Variant'), ('edition', 'Edition'), ('other', 'Other')], max_length=20)),
                ('anchor_text', models.TextField(blank=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_out', to='legal_documents.legaldocument')),
                ('target_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_in', to='legal_documents.legaldocument')),
                ('source_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relations_out', to='legal_documents.legaldocumentsection')),
            ],
            options={
                'indexes': [models.Index(fields=['target_external_id'], name='legal_docum_target__f17f5b_idx'), models.Index(fields=['source_document', 'relation_type'], name='legal_docum_source__1a667c_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_document', 'target_url', 'relation_type', 'source_section'), name='uniq_relation', nulls_distinct=False)],
            },
        ),
        migrations.AddIndex(
            model_name='legaldocumentversion',
            index=models.Index(fields=['document', 'content_hash'], name='legal_docum_documen_8b7c79_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocumentversion',
            index=django.contrib.postgres.indexes.GistIndex(fields=['valid_period'], name='version_valid_period_gist'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_version_number'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document',), name='one_current_version_per_document'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='chk_version_range'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], expressions=[('document', '='), ('valid_period', '&&')], name='no_overlapping_versions'),
        ),
        migrations.AddIndex(
            model_name='legaldocumentsection',
            index=models.Index(fields=['version', 'parent'], name='legal_docum_version_92fe2c_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocumentsection',
            index=models.Index(fields=['source_anchor'], name='legal_docum_source__cc5ca8_idx'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentsection',
            constraint=models.UniqueConstraint(fields=('version', 'order_index'), name='uniq_section_order'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['number_key'], name='legal_docum_number__d1dfe9_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['status'], name='legal_docum_status_376453_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['adopted_at'], name='legal_docum_adopted_b574f7_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['language', 'text_status'], name='legal_docum_languag_91de8b_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('title', name='gin_trgm_ops'), name='legaldoc_title_trgm'),
        ),
        migrations.AddConstraint(
            model_name='legaldocument',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_document_source_external'),
        ),
        migrations.AddConstraint(
            model_name='legaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'expired', 'not_yet_effective', 'draft', 'unknown'])), name='chk_document_status'),
        ),
        migrations.AddConstraint(
            model_name='legaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('text_status__in', ['ok', 'stub', 'needs_ocr', 'empty'])), name='chk_document_text_status'),
        ),
    ]
