# Generated by Django 5.2.17 on 2026-09-28 08:59

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_documents', '0002_integrity_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='expiry_observed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='observation_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='legaldocumentsection',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='section_path_gist'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentsection',
            constraint=models.UniqueConstraint(fields=('version', 'path'), name='uniq_section_path'),
        ),
    ]
