# Generated by Django 5.2.17 on 2026-09-28 09:38

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_documents', '0003_legaldocument_expiry_observed_on_and_more'),
        ('legal_sources', '0002_snapshot_immutable'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocumentAttachment',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary_pdf', 'Primary Pdf'), ('pdf_export', 'Pdf Export')], max_length=20)),
                ('source_url', models.CharField(max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='legal_documents.legaldocument')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='legal_sources.sourcesnapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'snapshot'), name='uniq_attachment')],
            },
        ),
    ]
