# Generated by Django 5.2.17 on 2026-09-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_documents', '0004_legaldocumentattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocumentattachment',
            name='role',
            field=models.CharField(choices=[('primary_pdf', 'Primary Pdf'), ('pdf_export', 'Pdf Export'), ('source_zip', 'Source Zip')], max_length=20),
        ),
    ]
