# Generated by Django 5.2.17 on 2026-09-28 08:36

import apps.common.ids
import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_extensions_and_functions"),
        ('organizations', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingProfile',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=200)),
                ('model_version', models.CharField(max_length=100)),
                ('dimension', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('distance_metric', models.CharField(choices=[('cosine', 'Cosine'), ('l2', 'L2'), ('ip', 'Inner Product')], default='cosine', max_length=10)),
                ('hnsw_m', models.PositiveSmallIntegerField(default=16)),
                ('hnsw_ef_construction', models.PositiveSmallIntegerField(default=64)),
                ('is_active', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_embedding_profile'), models.CheckConstraint(condition=models.Q(('dimension__gte', 1), ('dimension__lte', 2000)), name='chk_profile_dimension')],
            },
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='search.documentchunk')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('embedding_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embeddings', to='embeddings.embeddingprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['embedding_profile'], name='embeddings__embeddi_3ac3f1_idx'), models.Index(fields=['organization'], name='embeddings__organiz_73b93f_idx')],
                'constraints': [models.UniqueConstraint(fields=('chunk', 'embedding_profile'), name='uniq_chunk_profile')],
            },
        ),
    ]
