# Generated by Django 5.2.17 on 2026-09-28 11:38

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_sources', '0003_alter_sourcesnapshot_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategoryMap',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_key', models.CharField(max_length=300, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceStatisticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('total_documents', models.PositiveIntegerField()),
                ('header_total', models.PositiveIntegerField(blank=True, null=True)),
                ('consistent', models.BooleanField()),
                ('problems', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statistics_snapshots', to='legal_sources.legalsource')),
            ],
            options={
                'ordering': ['-captured_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'captured_at'), name='uniq_stats_source_captured')],
            },
        ),
    ]
